use_frameworks!

source 'https://github.com/CocoaPods/Specs.git' #include this if you will be referencing any public pods!

target 'NFSpotifyAuth_Example' do
  pod 'NFSpotifyAuth', :path => '../'
  pod 'Alamofire', '~> 5.1'
  pod 'NFImageView', '~> 0.2.3'

  target 'NFSpotifyAuth_Tests' do
    inherit! :search_paths

    
  end
end
